def options(ctx):
    pass

def configure(ctx):
    pass

def build(bld):
    bld.program(
        source = 'LZTreeMain.cpp',
        target = 'lztree',
        use    = 'LZTREE',
        include = '.')
